### ISSUE TITLE
Move mailing lists away from SF

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt.github.io#12]

**Comment by jleclanche** [comment]
Notes to self

 https://lists.sourceforge.net/mbox/lxde-list
https://sourceforge.net/p/lxde/admin/mailman/lxde-list/subscribers/display

**Comment by agaida** [comment]
Do we really want to have (a) mailing list(s) - discourse can act like one (and in fact it does, but is seldom used)

**Comment by jleclanche** [comment]
The plan was to move to discourse initially yes. Once upon a time there was talk of Github-based mailing lists but they never properly made it happen -- the forum stuff is too restricted.

If you can replace the ML with Discourse that's +1 from me.

**Comment by yan12125** [comment]
The mailing list mentioned on the website is replace by the link to GitHub Discussions in #54. The latter is more or less like a Discourse forum so I believe this issue is resolved. lxde-list is still useful for LXDE discussions.

(Side note: there was indeed a Discourse instance but it has been dead for some time https://github.com/lxqt/lxqt/issues/1829)
