### ISSUE TITLE
Can't see the selected text

### ISSUE THREAD

**Issue by ChungZH** [lxqt/lxqt.github.io#73]
##### Expected Behavior

I can see the selected text.
##### Current Behavior

I can't see the selected text.
##### Possible Solution

Change the `::selection background-color` (now is `FFF`)
##### Context

![2021-08-22_15-48](https://user-images.githubusercontent.com/42088872/130346949-01725a57-da1e-4a8c-a4ba-a702de56dc23.png)

**Comment by stefonarch** [comment]
For some reason in _base.scss
 ```$selected-background-color: #39F !global;	// #Note: Default light blue for selected background-colour``` doesn't work. 
Replacing    `$selected-background-color` works but is a hack:
```
@include selection()
	{
		color: $selected-color;
		background-color: #39F;
	}
```

**Comment by zealvurte** [comment]
Was just idly looking at what's changed over time with this and saw this issue, and I'm surprised this only came up now, as it's been wrong all along. 😮

https://github.com/lxqt/lxqt.github.io/blob/master/styles/lxqt.scss#L47 overrides the default `background-color` to `$color`, that's why. I'm not sure what my intent was at the time, but I think I probably meant for that to be `$link-color` instead. 🤦‍♂️

**Comment by stefonarch** [comment]
Thanks! So you're making a PR?
